### ISSUE TITLE
Hg37 support

### ISSUE THREAD

**Issue by jpaaso** [gatk-workflows/five-dollar-genome-analysis-pipeline#10]
Hi,

Is there a way to make this work with Hg37? Or is there a similar Hg37 pipeline available?

Thanks,
Juho

**Comment by bshifaw** [comment]
Hi Juho,

No there isn't a HG37 version. For possible workarounds please post your questions in the [GATK forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team) for the dev team can review. 
Thanks

**Comment by jpaaso** [comment]
Will do, thanks!
