### ISSUE TITLE
what is "five-dollar- genome-analysis" mean?

### ISSUE THREAD

**Issue by runningsnail2333** [gatk-workflows/five-dollar-genome-analysis-pipeline#14]
hi, I have a question: why does this title name "five-dollar-genome-analysis-pipeline"? does it mean the whole analysis cost 5 dollars? but  if the input ubam file is around 100G, does the whole analysis cost is  still  5 dollars ? thanks

**Comment by bshifaw** [comment]
Hi @runningsnail2333 
This blog post on the gatk site has a good description of the $5 pipeline, also feel free to post questions to [GATK forums](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team). 
	
[Run the germline GATK Best Practices Pipeline for $5 per genome ](https://software.broadinstitute.org/gatk/blog?id=11415)
