### ISSUE TITLE
What is "fingerprint_genotypes_file"

### ISSUE THREAD

**Issue by JavisPeng** [gatk-workflows/five-dollar-genome-analysis-pipeline#20]
I'm curious what's fingerprint_genotypes_file, which wdl file it appears in ?
```xml
"WholeGenomeGermlineSingleSample.references": {
    "fingerprint_genotypes_file": "gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf",
    "fingerprint_genotypes_index": "gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf.idx",
```

**Comment by bshifaw** [comment]
The following material is provided by the GATK Team. Please post any questions or concerns to one of our forum sites : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) or [Terra](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500432-General-Discussion) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).

Fingerprint genotype file is "essentially, genotype information from different parts of the genome", The file your passing to the workflow here is the fingerprint you want to compare your sample VCF to.  The file is used in the [Qc.wdl](https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/blob/70025d47d2aea47043effa63f4f5d619004c9c7c/tasks/Qc.wdl) subworkflow by the following tools: [CheckFingerprint](https://broadinstitute.github.io/picard/command-line-overview.html#CheckFingerprint) and [CrosscheckFingerprints](https://broadinstitute.github.io/picard/command-line-overview.html#CrosscheckFingerprints). The workflow that calls the tasks in the qc.wdl is the [AggregatedBamQC.wdl](https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/blob/70025d47d2aea47043effa63f4f5d619004c9c7c/tasks/AggregatedBamQC.wdl#L65) wdl.

Please direct questions to
