### ISSUE TITLE
BamToGvcf.wdl typo in local import

### ISSUE THREAD

**Issue by lmtani** [gatk-workflows/five-dollar-genome-analysis-pipeline#21]
First of all, thanks for making available this awesome workflow.

I think that this commented line:

https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/blob/a418352b4103c5ccdff099b63ec14866b0d5602d/tasks/BamToGvcf.wdl#L4

Should be:

`# import "GermlineVariantDiscovery.wdl" as Calling`

**Comment by bshifaw** [comment]
Fixed, thanks
